import { PostItColor } from "@/types/type";


export const defaultColors: PostItColor[] = [
  {
    name: "yellow",
    id: "yellow",
    hex: "#ffe640",
    rarity: "default",
    foldcolorhex: "#fef08a",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#B29B00",
  },
  {
    name: "pink",
    id: "pink",
    hex: "#FBB1F5",
    rarity: "default",
    foldcolorhex: "#FFC8FB",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#D82C82",
  },
  {
    name: "light-blue",
    id: "light-blue",
    hex: "#93c5fd",
    rarity: "default",
    foldcolorhex: "#b8e1ff",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#2775CC",
  }
];

export const allColors: PostItColor[] = [
  {
    name: "Yellow",
    id: "yellow",
    hex: "#ffe640",
    rarity: "default",
    foldcolorhex: "#fef08a",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#B29B00",
  },
  {
    name: "Pink",
    id: "pink",
    hex: "#FBB1F5",
    rarity: "default",
    foldcolorhex: "#FFC8FB",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#D82C82",
  },
  {
    name: "Light Blue",
    id: "light-blue",
    hex: "#93c5fd",
    rarity: "default",
    foldcolorhex: "#b8e1ff",
    SRB: [0, 0, 0],
    meaning: "",
    fontColor: "#2775CC",
  },
  {
    name: "Baby Purple",
    id: "baby-purple",
    hex: "#CFB1FB",
    rarity: "default",
    foldcolorhex: "#E2C7FF",
    SRB: [0, 0, 0],
    meaning: "A mind that is oriented towards discovery, a pioneer.",
    attributes: {
      class: "Curious",
      level: 1,
      description: "A soft and calming color, perfect for gentle reminders.",
    },
    fontColor: "#8654CF",
  },
  {
    id: "scarlet-surge",
    name: "Scarlet Surge",
    hex: "#de6464",
    rarity: "Rare",
    foldcolorhex: "#f19b9b",
    fontColor: "#000000",
    SRB: [30, 20, 50],
    meaning: "One who demands attention.",
    attributes: {
      class: "Dominant",
      level: 2,
      description: "Users who post bold, attention-grabbing content.",
    },
  },
  {
    id: "blush-harmony",
    name: "Blush Harmony",
    hex: "#f5d3dc",
    rarity: "Uncommon",
    foldcolorhex: "#fde9ef",
    fontColor: "#000000",
    SRB: [25, 50, 25],
    meaning: "One who creates safe spaces.",
    attributes: {
      class: "Empathy",
      level: 2,
      description: "Supportive users who foster emotional warmth.",
    },
  },
  {
    id: "zenith-clarity",
    name: "Zenith Clarity",
    hex: "#5DC5F2",
    rarity: "Common",
    foldcolorhex: "#c3e3fd",
    fontColor: "#000000",
    SRB: [45, 30, 25],
    meaning: "One who ensures peaceful dialogue.",
    attributes: {
      class: "Trust",
      level: 1,
      description: "Communicators who prioritize clear, uplifting discussions",
    },
  },
  {
    id: "tidal-muse",
    name: "Tidal Muse",
    hex: "#6bc6c9",
    rarity: "Epic",
    foldcolorhex: "#b6e8ea",
    fontColor: "#000000",
    SRB: [15, 65, 20],
    meaning: "One who defines art.",
    attributes: {
      class: "Modern",
      level: 3,
      description: "An artist with unique aesthetics.",
    },
  },
  {
    id: "verdant-revival",
    name: "Verdant Revival",
    hex: "#5bbd83",
    rarity: "Uncommon",
    foldcolorhex: "#a7eac1",
    fontColor: "#000000",
    SRB: [30, 20, 50],
    meaning: "One who mentors and renews.",
    attributes: {
      class: "Growth",
      level: 2,
      description: "Users who revive old threads or mentor newcomers.",
    },
  },
  {
    id: "solar-spark",
    name: "Solar Spark",
    hex: "#FF9F00",
    rarity: "Rare",
    foldcolorhex: "#ffd580",
    fontColor: "#000000",
    SRB: [40, 30, 30],
    meaning: "One who sparks adventures.",
    attributes: {
      class: "Vitality",
      level: 2,
      description: "Trendsetters who initiate challenges.",
    },
  },
  {
    id: "mirth-sprout",
    name: "Mirth Sprout",
    hex: "#9ebd5b",
    rarity: "Uncommon",
    foldcolorhex: "#d0e9a0",
    fontColor: "#000000",
    SRB: [10, 70, 20],
    meaning: "One who plays with curiosity.",
    attributes: {
      class: "Whimsy",
      level: 3,
      description: "Curious users who test new features.",
    },
  },
  {
    id: "gilded-hearth",
    name: "Gilded Hearth",
    hex: "#e3b36f",
    rarity: "Legendary",
    foldcolorhex: "#f3d9ab",
    fontColor: "#000000",
    SRB: [55, 25, 20],
    meaning: "One who comforts through memory.",
    attributes: {
      class: "Warmth",
      level: 3,
      description: "Users sharing personal stories and nostalgic content.",
    },
  },
  {
    id: "luna-veil",
    name: "Luna Veil",
    hex: "#e0d9f5",
    rarity: "Epic",
    foldcolorhex: "#f2edff",
    fontColor: "#000000",
    SRB: [10, 60, 30],
    meaning: "One who dreams in verse.",
    attributes: {
      class: "Spiritual",
      level: 3,
      description: "Dreamy creators with poetic or astrological themes.",
    },
  },
  {
    id: "crimson-whisper",
    name: "Crimson Whisper",
    hex: "#D82F57",
    rarity: "Rare",
    foldcolorhex: "#d86a7e",
    fontColor: "#ffffff",
    SRB: [25, 40, 35],
    meaning: "One who speaks from the soul.",
    attributes: {
      class: "Intimate",
      level: 2,
      description: "Users posting emotionally raw or sensual content.",
    },
  },
  {
    id: "terracotta-flame",
    name: "Terracotta Flame",
    hex: "#EF734A",
    rarity: "Rare",
    foldcolorhex: "#f38f6f",
    fontColor: "#ffffff",
    SRB: [50, 25, 25],
    meaning: "One who transforms through journey.",
    attributes: {
      class: "Earthbound",
      level: 2,
      description: "Adventure seekers sharing transformative experiences.",
    },
  },
  {
    id: "oak-resolve",
    name: "Oak Resolve",
    hex: "#EEB391",
    rarity: "Legendary",
    foldcolorhex: "#FFCCAF",
    fontColor: "#D58559",
    SRB: [60, 15, 25],
    meaning: "One who anchors wisdom.",
    attributes: {
      class: "Foundation",
      level: 3,
      description: "Advice givers and long-form writers.",
    },
  },
  {
    id: "jade-depth",
    name: "Jade Depth",
    hex: "#116650",
    rarity: "Rare",
    foldcolorhex: "#4ba289",
    fontColor: "#ffffff",
    SRB: [40, 40, 20],
    meaning: "One who balances community.",
    attributes: {
      class: "Mediator",
      level: 2,
      description: "Users who bridge communities or mediate conflicts.",
    },
  },
  {
    id: "misty-logic",
    name: "Misty Logic",
    hex: "#9e9e9d",
    rarity: "Common",
    foldcolorhex: "#d4d4d3",
    fontColor: "#000000",
    SRB: [35, 35, 30],
    meaning: "One who trusts in reason.",
    attributes: {
      class: "Analytic",
      level: 1,
      description: "Users who post data- or fact-based content.",
    },
  },
  {
    id: "royal-vision",
    name: "Royal Vision",
    hex: "#6432fa",
    rarity: "Epic",
    foldcolorhex: "#a28dff",
    fontColor: "#ffffff",
    SRB: [30, 40, 50],
    meaning: "One who inspires ambition.",
    attributes: {
      class: "Innovator",
      level: 3,
      description: "Aspirational users sharing success stories.",
    },
  },
  {
    id: "abyssal-insight",
    name: "Abyssal Insight",
    hex: "#003c5f",
    rarity: "Legendary",
    foldcolorhex: "#4689a1",
    fontColor: "#ffffff",
    SRB: [50, 20, 60],
    meaning: "One who dives into depth.",
    attributes: {
      class: "Expert",
      level: 3,
      description: "Users posting niche expertise with stability.",
    },
  },

];