"project_id": "785028"
"api_token": "186294ac72d8748cafecf89e3ee6aa304feb63b6e7c400a4efc233b3fabaa2a079e837047c7c2f10"

"base_path": "."
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "/locales/en/translation.json",
    "translation": "/locales/%two_letters_code%/%original_file_name%"
  }
]
